server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Optional: Handle error 404 by redirecting to index.html for SPA
    error_page 404 /index.html;
}
